export const homePageQuery = `query{
  homePage(id:"1PM7PyUnpvtdsjHsMyEKqY"){
    heroTitle,
    heroSubtitle,
    heroSubtitle2,
    heroButtonText,
    heroImage{
      url,
      description
    }
    ourNumbers{
      tag,
      title
      description
      imagesCollection{
        items{
          title,
          url
        }
      }
      cardsCollection{
        items{
          title
          description
          counter
          symbol
          
        }
      }
      buttonText
    }
    ourNumbersTitleList
    whyRe{
      tag,
      title
      description
      imagesCollection{
        items{
          title,
          url
        }
      }
      cardsCollection{
        items{
          title
          description
          image{
            url
          }
        }
      }
      buttonText
    }
    whyConsultation{
      tag
      title
      description
      imagesCollection{
        items{
          title,
          url
        }
      }
      cardsCollection{
        items{
          title
          description
          image{
            url
          }
          bulletPoints
        }
      }
    }
    whyInfiniaSolar{
      tag
      title
      description
      imagesCollection{
        items{
          title,
          url
        }
      }
      cardsCollection{
        items{
          title
          description
          image{
            url
          }
        }
      }
    }
    testimonials{
      tag
      title
      cardsCollection{
        items{
          title
          description
          counter
          image{
            url
          }
          bulletPoints
        }
      }
    }
    customerSection{
      tag
      title
      description
      imagesCollection{
        items{
          title,
          url
        }
      }
    }
    mapSection{
      title,
      description
    }
  }
}`;
